<?php
/**
 * Plugin Name: TM Product Wishlist
 * Description: Lightweight WooCommerce product wishlist with shareable lists.
 * Version: 1.3.0
 * Author: Tailor-Made UK
 */

if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

// Basic constants
define( 'TMWL_PATH', plugin_dir_path( __FILE__ ) );
define( 'TMWL_URL',  plugin_dir_url( __FILE__ ) );
define( 'TMWL_VERSION', '1.3.0' );

// Composer autoload (generated by composer install)
if ( file_exists( TMWL_PATH . 'vendor/autoload.php' ) ) {
    require_once TMWL_PATH . 'vendor/autoload.php';
}

// Import classes
use TMWishlist\TMWL_Assets;
use TMWishlist\TMWL_Main;
use TMWishlist\TMWL_ComparisonManager;

// Bootstrap plugin classes
add_action( 'plugins_loaded', function() {
    TMWL_Assets::init();
    TMWL_Main::init();
    TMWL_ComparisonManager::init();
});

// Create DB table when plugin is activated
register_activation_hook( __FILE__, [ 'TMWishlist\\TMWL_ComparisonManager', 'create_table' ] );