name: Deploy to Staging

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.TM_STORE_PASS }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to Staging
        run: |
          rsync -azc --delete \
            --omit-dir-times \
            --no-times \
            --no-perms \
            --no-owner \
            --no-group \
            --exclude=".git" \
            --exclude=".github" \
            --exclude=".env" \
            --exclude=".DS_Store" \
            --exclude="vendor/" \
            -e "ssh -i ~/.ssh/id_ed25519" \
            ./ \
            ${{ secrets.TM_STORE_SSH_USER }}@${{ secrets.SSH_HOST }}:${{ vars.STAGING_DEPLOY_PATH }}

      - name: Complete
        run: echo "Staging deployment complete."